# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=AdBlock Lean Web UI
LUCI_URL:=https://github.com/rickparrish/luci-app-adblock-lean/
LUCI_DESCRIPTION:=Provides Web UI for adblock-lean service.
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-adblock-lean
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Rick Parrish <luci-app-adblock-lean@rickparrish.ca>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
