'use strict';

return L.Class.extend({
	baseUrl:  'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/',
	
    blocklists: [
		{ filename: 'light', name: 'Multi LIGHT' },
		{ filename: 'multi', name: 'Multi NORMAL' },
		{ filename: 'pro', name: 'Multi PRO' },
		{ filename: 'pro.mini', name: 'Multi PRO mini' },
		{ filename: 'pro.plus', name: 'Multi PRO++' },
		{ filename: 'pro.plus.mini', name: 'Multi PRO++ mini ' },
		{ filename: 'ultimate', name: 'Multi ULTIMATE' },
		{ filename: 'ultimate.mini', name: 'Multi ULTIMATE mini ' },
		{ filename: 'fake', name: 'Fake' },
		{ filename: 'popupads', name: 'Pop-Up Ads' },
		{ filename: 'tif', name: 'Threat Intelligence Feeds' },
		{ filename: 'tif.medium', name: 'Threat Intelligence Feeds - Medium' },
		{ filename: 'tif.mini', name: 'Threat Intelligence Feeds - Mini' },
		{ filename: 'doh-vpn-proxy-bypass', name: 'DoH/VPN/TOR/Proxy Bypass' },
		{ filename: 'doh', name: 'Encrypted DNS Servers' },
		{ filename: 'nosafesearch', name: 'Safesearch not supported' },
		{ filename: 'dyndns', name: 'Dynamic DNS' },
		{ filename: 'hoster', name: 'Badware Hoster' },
		{ filename: 'anti.piracy', name: 'Anti Piracy' },
		{ filename: 'gambling', name: 'Gambling' },
		{ filename: 'gambling.medium', name: 'Gambling - Medium' },
		{ filename: 'gambling.mini', name: 'Gambling - Mini' },
		{ filename: 'native.amazon', name: 'Native Tracker - Amazon' },
		{ filename: 'native.apple', name: 'Native Tracker - Apple' },
		{ filename: 'native.huawei', name: 'Native Tracker - Huawei' },
		{ filename: 'native.winoffice', name: 'Native Tracker - Microsoft' },
		{ filename: 'native.tiktok', name: 'Native Tracker - TikTok' },
		{ filename: 'native.tiktok.extended', name: 'Native Tracker - TikTok Aggressive' },
		{ filename: 'native.lgwebos', name: 'Native Tracker - LG webOS' },
		{ filename: 'native.vivo', name: 'Native Tracker - Vivo' },
		{ filename: 'native.oppo-realme', name: 'Native Tracker - OPPO/Realme' },
		{ filename: 'native.xiaomi', name: 'Native Tracker - Xiaomi' },
	],
});